name: ${project.name}
version: ${project.version}
description: ${project.description}
api-version: 1.13

author: Ullarah

softdepend: [WorldEdit, WorldGuard]

main: ${project.groupId}.${project.artifactId}.ChestInit

commands:
  chest:
    description: Views the global chest menu.
    usage: |
      <command> toggle <chest> : Puts the chest type in/out of service.
  dchest:
    description: Views the donation chest.
    usage: |
      <command> : Views the donation chest.
      <command> random : Places random items in the donation chest.
      <command> reset : Clears the entire donation chest.
  echest:
    description: Views the enchantment chest.
    usage: |
      <command> : Views the enchantment chest.
  hchest:
    description: Views the hold chest.
    usage: |
      <command> : Views the hold chest.
      <command> view <player>: Views the hold chest of a player.
      <command> reset <player>: Resets the hold chest of a player.
  mchest:
    description: Views the money chest.
    usage: |
      <command> : Views the money chest.
  rchest:
    description: Views the random chest.
    usage: |
      <command> : Views the random chest.
  schest:
    description: Views the shuffle chest.
    usage: |
      <command> : Views the shuffle chest.
  vchest:
    description: Views the vault chest.
    usage: |
      <command> : Views the vault chest.
      <command> upgrade : Upgrades the vault chest slots.
      <command> view <player>: Views the vault chest of a player.
      <command> reset <player>: Resets the vault chest of a player.
  wchest:
    description: Views the swapping chest.
    usage: |
      <command> : Views the swapping chest.
  xchest:
    description: Views the experience chest.
    usage: |
      <command> : Views the experience chest.

permissions:
  chest.access:
    description: Grants access to all chests.
  chest.staff:
    description: Grants all of the staff commands.
    children:
      chest.bypass: true
      chest.random: true
      chest.reset: true
      chest.view: true