name: ${project.name}
version: ${project.version}
description: ${project.description}
api-version: 1.18

author: Ullarah

main: ${project.groupId}.${project.artifactId}.RocketInit

softdepend: [WorldEdit, WorldGuard, Vault]

commands:
  rocket:
    description: Display Rocket Help.
    usage: |
      <command> : Shows Help.
      <command> chest : Shows Rocket Components.
      <command> fuel : Show contents of fuel jacket.
  fuel:
    description: Display fuel jacket.
    usage: |
      <command> : Show contents of fuel jacket.

permissions:
  rocket.lenientflight:
    description: Allow player to fly with no boots attached, if turned on by an external command
    default: false
  rocket.staff:
    description: Grants staff extra Rocket Boot commands.
    children:
      rocket.chest: true
      rocket.clairvoyant: true
