name: ${project.name}
version: ${project.version}
api-version: 1.21
description: ${project.description}

author: Ullarah

main: ${project.groupId}.${project.artifactId}.TabInit

commands:
  utab:
    description: Main plugin command.
    usage: |
      <command> : Display Total and Current Messages.
      <command> reload : Reload Tab Messages.

permissions:
  utab.commands:
    description: Grants use of tab commands.
