name: ${project.name}
version: ${project.version}
description: ${project.description}
api-version: 1.13

author: Ullarah

softdepend: [WorldEdit, WorldGuard]

main: ${project.groupId}.${project.artifactId}.MagicInit

commands:
  hoe:
    description: Hoe Crafting Command
    usage: |
      <command> : Gives a magical hoe.

permissions:
  umagic.danger:
    description: Allows usage of dangerous conversions
  umagic.usage:
    description: Allows usage of the Magic Hoe
  umagic.bypass:
    description: Bypass WorldGuard region access
  umagic.gethoe:
    description: Obtain a Magic Hoe without crafting